// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AsrModel = "Qwen3-ASR-0.6B" | "Qwen3-ASR-1.7B" | "cohere-transcribe-03-2026";
