// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlignModel } from "./AlignModel";
import type { AsrModel } from "./AsrModel";
import type { DemucsModel } from "./DemucsModel";
import type { Provider } from "./Provider";
import type { SubtitleBurnMode } from "./SubtitleBurnMode";
import type { SubtitleLengthPreset } from "./SubtitleLengthPreset";
import type { SubtitleRenderStyle } from "./SubtitleRenderStyle";
import type { TerminologyGroup } from "./TerminologyGroup";

export type SavedSettings = { provider: Provider, chunkTargetSeconds: number, subtitleLengthPreset: SubtitleLengthPreset, asrModel: AsrModel, alignModel: AlignModel, demucsModel: DemucsModel, enableVocalSeparation: boolean, translateApiKey: string, translateBaseUrl: string, translateModel: string, llmConcurrency: number, terminologyGroups: Array<TerminologyGroup>, activeTerminologyGroupId: string, enableSubtitleBeautify: boolean, enableClickSound: boolean, autoBurnHardSubtitle: boolean, subtitleBurnMode: SubtitleBurnMode, subtitleRenderStyle: SubtitleRenderStyle, flatSrtOutput: boolean, flatSrtItems: Array<SubtitleBurnMode>, enableVisionAssist: boolean, };
