// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtitleRenderStyle } from "./SubtitleRenderStyle";
import type { TerminologyGroup } from "./TerminologyGroup";

export type SavedSettings = { provider: string, chunkTargetSeconds: number, subtitleLengthPreset: string, asrModel: string, alignModel: string, demucsModel: string, enableVocalSeparation: boolean, translateApiKey: string, translateBaseUrl: string, translateModel: string, llmConcurrency: number, terminologyGroups: Array<TerminologyGroup>, enableTerminology: boolean, enableSubtitleBeautify: boolean, enableClickSound: boolean, autoBurnHardSubtitle: boolean, subtitleBurnMode: string, subtitleRenderStyle: SubtitleRenderStyle, };
