// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SavedSettings } from "./SavedSettings";

export type SaveAppSettingsRequest = { settings: SavedSettings, };
