// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubtitleLineStyle = { fontFamily: string, fontSize: number, primaryColor: string, outlineColor: string, backColor: string, outline: number, shadow: number, borderStyle: string, borderOpacity: number, };
