// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SubtitleLayoutStyle = { marginV: number, alignment: number, bilingualLineGap: number, };
