// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubtitleLayoutStyle } from "./SubtitleLayoutStyle";
import type { SubtitleLineStyle } from "./SubtitleLineStyle";

export type SubtitleRenderStyle = { source: SubtitleLineStyle, target: SubtitleLineStyle, layout: SubtitleLayoutStyle, };
