// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminologyTerm = { id: string, origin: string, target: string, note: string, };
