// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminologyTerm } from "./TerminologyTerm";

export type TerminologyGroup = { id: string, name: string, terms: Array<TerminologyTerm>, };
